<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ShinymasDl.Core\ShinymasDl.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="3.0.0-preview.7.26381.103" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>shinymas-dl</AssemblyName>
    <RootNamespace>ShinymasDl.Cli</RootNamespace>
  </PropertyGroup>

</Project>
